CREATE TABLE list (
	id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
	name VARCHAR(256) NOT NULL
	boardId UUID REFERENCES boards(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE card (
	id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
	title VARCHAR(256) NOT NULL,
	description VARCHAR(256) NOT NULL,
	due_date DATE,
	listId UUID REFERENCES list(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE card_user (
	id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
	userId UUID REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
	isOwner BOOLEAN DEFAULT false
);